### Create a new regular user
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Renato Lomba",
  "email": "rntlomba6@gmail.com",
  "password": "123456"
}

### Create a new partner user
POST http://localhost:3000/partner/users
Content-Type: application/json

{
  "name": "Renato Lomba",
  "email": "rntlomba7@gmail.com",
  "password": "123456"
}

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "rntlomba7@gmail.com",
  "password": "123456"
}

### Create partner
POST http://localhost:3000/partners
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsIm5hbWUiOiJSZW5hdG8gTG9tYmEiLCJlbWFpbCI6InJudGxvbWJhNUBnbWFpbC5jb20iLCJyb2xlcyI6WyJQQVJUTkVSIl0sImNyZWF0ZWRBdCI6IjIwMjQtMDYtMTZUMjI6NTQ6MTAuNzkzWiIsInVwZGF0ZWRBdCI6IjIwMjQtMDYtMTZUMjI6NTQ6MTAuNzkzWiIsImlhdCI6MTcxODU4NTQ2OCwiZXhwIjoxNzE4NTg5MDY4fQ.1lpRTf_fQn5avfIuLhLUBlSC7OqTxDXmaIRmAF-_ymw

{
  "name": "Parceiro 3"
}

### Get user partners
GET http://localhost:3000/partners
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsIm5hbWUiOiJSZW5hdG8gTG9tYmEiLCJlbWFpbCI6InJudGxvbWJhNkBnbWFpbC5jb20iLCJyb2xlcyI6WyJVU0VSIl0sImNyZWF0ZWRBdCI6IjIwMjQtMDYtMTZUMjI6NTk6NDguNjg1WiIsInVwZGF0ZWRBdCI6IjIwMjQtMDYtMTZUMjI6NTk6NDguNjg1WiIsImlhdCI6MTcxODU4OTQ3NiwiZXhwIjoxNzE4NTkzMDc2fQ.mpWb4C0d19HOqD8TY6agUFBSjHzEWMwKMECfEa09m8E

### Create a event
POST http://localhost:3000/events
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsIm5hbWUiOiJSZW5hdG8gTG9tYmEiLCJlbWFpbCI6InJudGxvbWJhNkBnbWFpbC5jb20iLCJyb2xlcyI6WyJVU0VSIl0sImNyZWF0ZWRBdCI6IjIwMjQtMDYtMTZUMjI6NTk6NDguNjg1WiIsInVwZGF0ZWRBdCI6IjIwMjQtMDYtMTZUMjI6NTk6NDguNjg1WiIsImlhdCI6MTcxODU4OTQ3NiwiZXhwIjoxNzE4NTkzMDc2fQ.mpWb4C0d19HOqD8TY6agUFBSjHzEWMwKMECfEa09m8E
x-tenant-id: 2

{
  "name": "Evento 3",
  "description": "Teste evento 3",
  "startDate": "2024-06-16"
}

### Get partner events
GET http://localhost:3000/events
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsIm5hbWUiOiJSZW5hdG8gTG9tYmEiLCJlbWFpbCI6InJudGxvbWJhNkBnbWFpbC5jb20iLCJyb2xlcyI6WyJVU0VSIl0sImNyZWF0ZWRBdCI6IjIwMjQtMDYtMTZUMjI6NTk6NDguNjg1WiIsInVwZGF0ZWRBdCI6IjIwMjQtMDYtMTZUMjI6NTk6NDguNjg1WiIsImlhdCI6MTcxODU4OTQ3NiwiZXhwIjoxNzE4NTkzMDc2fQ.mpWb4C0d19HOqD8TY6agUFBSjHzEWMwKMECfEa09m8E
x-tenant-id: 2
