## Create a new regular user
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Renato Lomba",
  "email": "rntlomba6@gmail.com",
  "password": "123456"
}

## Create a new partner user
POST http://localhost:3000/partner/users
Content-Type: application/json

{
  "name": "Renato Lomba",
  "email": "rntlomba7@gmail.com",
  "password": "123456"
}

## Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "rntlomba6@gmail.com",
  "password": "123456"
}

## Create partner
POST http://localhost:3000/partners
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsIm5hbWUiOiJSZW5hdG8gTG9tYmEiLCJlbWFpbCI6InJudGxvbWJhNkBnbWFpbC5jb20iLCJyb2xlcyI6WyJVU0VSIl0sImNyZWF0ZWRBdCI6IjIwMjQtMDYtMTZUMjI6NTk6NDguNjg1WiIsInVwZGF0ZWRBdCI6IjIwMjQtMDYtMTZUMjI6NTk6NDguNjg1WiIsImlhdCI6MTcxODU4NTI1MywiZXhwIjoxNzE4NTg4ODUzfQ.9JtmOtK0XQiiPWEA6JCf1ZSUzH_dthXWf2Ft1OwMLpc

{
  "name": "Parceiro 2"
}
