## Create a new regular user
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Renato Lomba",
  "email": "rntlomba4@gmail.com",
  "password": "123456"
}

## Create a new partner user
POST http://localhost:3000/partner/users
Content-Type: application/json

{
  "name": "Renato Lomba",
  "email": "rntlomba5@gmail.com",
  "password": "123456"
}

